### PR TITLE
[Nuclio] Create function: minor redesign

### PR DESCRIPTION
**Pull request by YarovoiVadym**
Implements Trello ticket [[Nuclio] Create function: minor redesign](https://trello.com/c/OvO7C6pK)

### CODE REVIEW

**Comment by eran-nussbaum** [comment]
Bug:

##### Description
The "Create" button is always disabled.

##### Steps to reproduce
1. Go to "Create new function" screen in Nuclio
2. Select a template
3. Enter name and select a project

##### Expected result
The "Create" button should become enabled.

##### Actual result
The "Create" button remains disabled.

##### Screenshot(s)
image

**Comment by eran-nussbaum** [comment]
Bug:

##### Description
Selected template is displayed behind non-selected template (regarding z-index).

##### Steps to reproduce
1. Go to "Create new function" screen in Nuclio
2. Select a template on the first line of templates
3. Hover on a template right below it on the next line of templates

##### Expected result
The selected template should be displayed on top of the non-selected template (z-index).

##### Actual result
The selected template is displayed behind the non-selected template (z-index).

Note: when the selected template is on a line lower than the the non-selected template, it works properly. See the next video screen capture for demonstration.

##### Screenshot(s)
image

**Comment by eran-nussbaum** [comment]
Missing implementation:
The new ✕ (close) button was not implemented.
It should be added, and then the "Cancel" button should be removed (in all 3 tabs, From Template, From Scratch, and Import).

**Comment by eran-nussbaum** [comment]
Bug:

##### Description
Space is not efficiently used to display as many templates on a line as possible.

##### Steps to reproduce
1. Go to "Create a new function" screen in Nuclio
2. Reduce the width of the web browser's tab's viewport.

##### Expected result
In any width of the viewport, the templates should be spread along the line and fill the empty space with as many templates as possible.

##### Actual result
There is empty space on each line that is big enough to contain at least one more template, but t does not contain any. (see attached screenshot for demonstration).

##### Screenshot(s)
image

**Comment by eran-nussbaum** [comment]
Bug:

##### Description
Vertical space between two lines of templates is not according to design.

##### Steps to reproduce
1. Go to "Create new function" screen in Nuclio
2. Look at the space between two lines of templates.

##### Expected result
The space should be 14 pixels.

##### Actual result
The space is 30 pixels.

##### Screenshot(s)
Expected:
image

Actual (in orange):
image

**Comment by YarovoiVadym** [comment]
> Bug:
> 
> ##### Description
> The "Create" button is always disabled when reaching the screen from Projects screen.
> 
> ##### Steps to reproduce
> 1. Go to Projects screen in Nuclio
> 2. Click on "Create function" button
> 3. Select a template
> 4. Enter name and select a project
> 
> ##### Expected result
> The "Create" button should become enabled.
> 
> ##### Actual result
> The "Create" button remains disabled.
> 
> Note: the bug does not reproduce when getting into "Create new function" screen from the function list screen of a specific project.
> 
> ##### Screenshot(s)
> image

I can't reproduce it.

**Comment by eran-nussbaum** [comment]
> > Bug:
> > ##### Description
> > The "Create" button is always disabled when reaching the screen from Projects screen.
> > ##### Steps to reproduce
> > 
> > 1. Go to Projects screen in Nuclio
> > 2. Click on "Create function" button
> > 3. Select a template
> > 4. Enter name and select a project
> > 
> > ##### Expected result
> > The "Create" button should become enabled.
> > ##### Actual result
> > The "Create" button remains disabled.
> > Note: the bug does not reproduce when getting into "Create new function" screen from the function list screen of a specific project.
> > ##### Screenshot(s)
> > image
> 
> I can't reproduce it.

It reproduces when using Chrome's auto-fill feature to fill in the value in the "Name" field.
image

**Pull request merged**
